// Notification types
export const INITIATED_CLASS = 'INITIATED_CLASS';
// 'ACCEPT_REQUEST REJECTED_REQUEST START_CLASS'
export const ACCEPT_REQUEST = 'ACCEPT_REQUEST';
export const REJECTED_REQUEST = 'REJECTED_REQUEST';
export const START_CLASS = 'START_CLASS';
export const FINISH_CLASS = 'FINISH_CLASS';
