name: Github action deploy
on:
  push:
    branches:
      - master

jobs:
  deploy-backend:
    name: Deploy backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Action
        uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
  
  deploy-frontend:
    name: Deploy 
    needs: [deploy-backend]
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'